Task: Update dependencies
leinardi/Forlago pull request #50
Opened 2024-07-01 07:01 UTC by jarroyoesp

### Pull request checklist

- [ ] I have **rebased** this branch on top of the destination branch (usually `master`)
- [ ] I have executed locally `./gradlew spotlessApply check` *before creating the commit* and it has run successfully
- [ ] My contribution is fully baked and ready to be merged as is
- [ ] I have performed a self-review of my own code
- [ ] These changes are in compliance with [the coding style](/CODING_STYLE.md) of this project
- [ ] There are no `WIP` commits in this PR
- [ ] If there are changes to the UI, I have uploaded at least one screenshot of every UI change

### Type of Changes

|     | Type                   |
|-----|------------------------|
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
|     | :scroll: Docs          |

### Screenshots

2024-07-01 09:32 UTC, jarroyoesp commented
Hey @leinardi I don't know why Espresso tests failing with timeout, Emulators and Github actions don't get along, do we merge the branch anyway?

2024-07-22 08:53 UTC, leinardi commented
Hey @jarroyoesp, CI Espresso is failing because they don't run well on the GitHub runners. I applied to the open source program of SauceLabs but never got an answer back. I should probably disable them but I'm still hoping that one day GitHub will make them work.

We can merge after I finish the review.

2024-07-22 09:02 UTC, leinardi requested changes

2024-07-26 07:38 UTC, jarroyoesp commented on gradle/libs.versions.toml
> +process-phoenix = "com.jakewharton:process-phoenix:3.0.0"
Oh true, I didn't notice that the following ones weren't plugins either. Enjoy the holidays man!

2024-08-08 10:10 UTC, leinardi approved these changes

2024-08-08 10:10 UTC, merged